.TH Lander 6l
.SH NAME
lander \- the arcade game
.SH DESCRIPTION
.I Lander
is an implementation of the ancient ``lunar lander'' arcade
game.
.PP
The object of the game is to gently land a lunar module on
the lunar surface.  Landing with a vertical velocity greater
than 5 metres per second will generally result in fragmentation of the
lander and loss of cabin pressure!
.PP
Scoring is based on which landing pad you choose, how much
fuel you conserved during landing and the difficulty factor
of landing from higher entry velocities as the game progresses.
.PP
Operating instructions are provided on the initial screen of
.I lander.
A high score file is maintained.
.SH BUGS
None known, but please send bug reports to {utzoo,utcsri,lsuc}!hcr!stacey.
.SH AUTHOR
Stacey Campbell \- HCR Corporation, Toronto, Canada, 1989.
.SH DISCLAIMER
Lander is copyright 1989 by HCR Corporation, Toronto, Ontario, Canada.
Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies.
.PP
HCR  Corporation  disclaims all  warranties with regard to
this software. Use at your own risk.
